/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeProjetRouteImport } from './routes/_home/projet'
import { Route as HomeExperienceRouteImport } from './routes/_home/experience'
import { Route as HomeEducationRouteImport } from './routes/_home/education'
import { Route as HomeContactRouteImport } from './routes/_home/contact'
import { Route as HomeAboutRouteImport } from './routes/_home/about'
import { Route as AdminUserRouteImport } from './routes/_admin/user'
import { Route as AdminProjectRouteImport } from './routes/_admin/project'
import { Route as AdminMessagesRouteImport } from './routes/_admin/messages'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeProjetRoute = HomeProjetRouteImport.update({
  id: '/projet',
  path: '/projet',
  getParentRoute: () => HomeRoute,
} as any)
const HomeExperienceRoute = HomeExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => HomeRoute,
} as any)
const HomeEducationRoute = HomeEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => HomeRoute,
} as any)
const HomeContactRoute = HomeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => HomeRoute,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeRoute,
} as any)
const AdminUserRoute = AdminUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectRoute = AdminProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/messages': typeof AdminMessagesRoute
  '/project': typeof AdminProjectRoute
  '/user': typeof AdminUserRoute
  '/about': typeof HomeAboutRoute
  '/contact': typeof HomeContactRoute
  '/education': typeof HomeEducationRoute
  '/experience': typeof HomeExperienceRoute
  '/projet': typeof HomeProjetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/messages': typeof AdminMessagesRoute
  '/project': typeof AdminProjectRoute
  '/user': typeof AdminUserRoute
  '/about': typeof HomeAboutRoute
  '/contact': typeof HomeContactRoute
  '/education': typeof HomeEducationRoute
  '/experience': typeof HomeExperienceRoute
  '/projet': typeof HomeProjetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_home': typeof HomeRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/messages': typeof AdminMessagesRoute
  '/_admin/project': typeof AdminProjectRoute
  '/_admin/user': typeof AdminUserRoute
  '/_home/about': typeof HomeAboutRoute
  '/_home/contact': typeof HomeContactRoute
  '/_home/education': typeof HomeEducationRoute
  '/_home/experience': typeof HomeExperienceRoute
  '/_home/projet': typeof HomeProjetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/messages'
    | '/project'
    | '/user'
    | '/about'
    | '/contact'
    | '/education'
    | '/experience'
    | '/projet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/messages'
    | '/project'
    | '/user'
    | '/about'
    | '/contact'
    | '/education'
    | '/experience'
    | '/projet'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_home'
    | '/login'
    | '/_admin/dashboard'
    | '/_admin/messages'
    | '/_admin/project'
    | '/_admin/user'
    | '/_home/about'
    | '/_home/contact'
    | '/_home/education'
    | '/_home/experience'
    | '/_home/projet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HomeRoute: typeof HomeRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/projet': {
      id: '/_home/projet'
      path: '/projet'
      fullPath: '/projet'
      preLoaderRoute: typeof HomeProjetRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/experience': {
      id: '/_home/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof HomeExperienceRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/education': {
      id: '/_home/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof HomeEducationRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/contact': {
      id: '/_home/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof HomeContactRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/about': {
      id: '/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_admin/user': {
      id: '/_admin/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AdminUserRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/project': {
      id: '/_admin/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof AdminProjectRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/messages': {
      id: '/_admin/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminProjectRoute: typeof AdminProjectRoute
  AdminUserRoute: typeof AdminUserRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminProjectRoute: AdminProjectRoute,
  AdminUserRoute: AdminUserRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface HomeRouteChildren {
  HomeAboutRoute: typeof HomeAboutRoute
  HomeContactRoute: typeof HomeContactRoute
  HomeEducationRoute: typeof HomeEducationRoute
  HomeExperienceRoute: typeof HomeExperienceRoute
  HomeProjetRoute: typeof HomeProjetRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeAboutRoute: HomeAboutRoute,
  HomeContactRoute: HomeContactRoute,
  HomeEducationRoute: HomeEducationRoute,
  HomeExperienceRoute: HomeExperienceRoute,
  HomeProjetRoute: HomeProjetRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HomeRoute: HomeRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
