/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeProjetRouteImport } from './routes/_home/projet'
import { Route as HomeExperienceRouteImport } from './routes/_home/experience'
import { Route as HomeEducationRouteImport } from './routes/_home/education'
import { Route as HomeContactRouteImport } from './routes/_home/contact'
import { Route as HomeAboutRouteImport } from './routes/_home/about'

const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeProjetRoute = HomeProjetRouteImport.update({
  id: '/projet',
  path: '/projet',
  getParentRoute: () => HomeRoute,
} as any)
const HomeExperienceRoute = HomeExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => HomeRoute,
} as any)
const HomeEducationRoute = HomeEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => HomeRoute,
} as any)
const HomeContactRoute = HomeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => HomeRoute,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof HomeAboutRoute
  '/contact': typeof HomeContactRoute
  '/education': typeof HomeEducationRoute
  '/experience': typeof HomeExperienceRoute
  '/projet': typeof HomeProjetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof HomeAboutRoute
  '/contact': typeof HomeContactRoute
  '/education': typeof HomeEducationRoute
  '/experience': typeof HomeExperienceRoute
  '/projet': typeof HomeProjetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_home': typeof HomeRouteWithChildren
  '/_home/about': typeof HomeAboutRoute
  '/_home/contact': typeof HomeContactRoute
  '/_home/education': typeof HomeEducationRoute
  '/_home/experience': typeof HomeExperienceRoute
  '/_home/projet': typeof HomeProjetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/education'
    | '/experience'
    | '/projet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/education' | '/experience' | '/projet'
  id:
    | '__root__'
    | '/'
    | '/_home'
    | '/_home/about'
    | '/_home/contact'
    | '/_home/education'
    | '/_home/experience'
    | '/_home/projet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/projet': {
      id: '/_home/projet'
      path: '/projet'
      fullPath: '/projet'
      preLoaderRoute: typeof HomeProjetRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/experience': {
      id: '/_home/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof HomeExperienceRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/education': {
      id: '/_home/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof HomeEducationRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/contact': {
      id: '/_home/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof HomeContactRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/about': {
      id: '/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface HomeRouteChildren {
  HomeAboutRoute: typeof HomeAboutRoute
  HomeContactRoute: typeof HomeContactRoute
  HomeEducationRoute: typeof HomeEducationRoute
  HomeExperienceRoute: typeof HomeExperienceRoute
  HomeProjetRoute: typeof HomeProjetRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeAboutRoute: HomeAboutRoute,
  HomeContactRoute: HomeContactRoute,
  HomeEducationRoute: HomeEducationRoute,
  HomeExperienceRoute: HomeExperienceRoute,
  HomeProjetRoute: HomeProjetRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
